configured_endpoints: 96
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/datamini%2Fasktable-5431edd8fc296f7bda00b9dd59dade97af9cac92d2f988b2ca13f1aad131c8b8.yml
openapi_spec_hash: 206d7bd1eceab32b3a7fa1ac11fc47e0
config_hash: a572ab842ea60ce13f1d1a1358440cbe
